SERVER_SRC_FILES = \
$(SERVER_DIR)$(INPUT_DIR)/utilities/ConditionVariable.java \
$(SERVER_DIR)$(INPUT_DIR)/utilities/IO.java \
$(SERVER_DIR)$(INPUT_DIR)/utilities/ProcessCommunicator.java \
$(SERVER_DIR)$(INPUT_DIR)/utilities/ColumnType.java \
$(SERVER_DIR)$(INPUT_DIR)/utilities/InitFileCommunicator.java \
$(SERVER_DIR)$(INPUT_DIR)/server/GapListLoader.java \
$(SERVER_DIR)$(INPUT_DIR)/server/MusicTrack.java \
$(SERVER_DIR)$(INPUT_DIR)/server/ServerFactory.java \
$(SERVER_DIR)$(INPUT_DIR)/server/ConnectionBroadcast.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetNextVideoURLCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetCurrentTrackCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SaveGapListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/UnknownCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GapListTrackUpCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetLoadGapListStatusCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SetAsPlayerCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SeekBackwardCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/ChangeGapListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/AddSongToOtherListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/DeleteAllVotesCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetGapListsCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SwitchNotifyStatusCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SetPermissionCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetCurrentGapListNameCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetCurrentPlayerCountCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetCurrentClientCountCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetTitleOfGapListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/CheckIfReadyCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/NotifyClientCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/RegisterCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/DeleteGapListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/VoteForSongCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GetCurrentPlaybackStatusCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/RemoveVoteCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/PauseResumeCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/PlayerFinishedCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SkipCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/GapListTrackDownCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/Command.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/YoutubeCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/SeekForwardCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/commands/DeleteFromListCommand.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/CommandHandler.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/Connection.java \
$(SERVER_DIR)$(INPUT_DIR)/server/connectivity/ConnectionWaiter.java \
$(SERVER_DIR)$(INPUT_DIR)/server/VotingController.java \
$(SERVER_DIR)$(INPUT_DIR)/server/YTJBServer.java \
$(SERVER_DIR)$(INPUT_DIR)/server/Server.java \
$(SERVER_DIR)$(INPUT_DIR)/server/player/MusicPlayer.java \
$(SERVER_DIR)$(INPUT_DIR)/server/player/ClientPlayer.java \
$(SERVER_DIR)$(INPUT_DIR)/server/player/TrackScheduler.java \
$(SERVER_DIR)$(INPUT_DIR)/server/player/OMXPlayer.java \
$(SERVER_DIR)$(INPUT_DIR)/server/URLParser.java

SERVER_CLASS_FILES = \
$(SERVER_DIR)$(OUTPUT_DIR)/utilities/ConditionVariable.class \
$(SERVER_DIR)$(OUTPUT_DIR)/utilities/IO.class \
$(SERVER_DIR)$(OUTPUT_DIR)/utilities/ProcessCommunicator.class \
$(SERVER_DIR)$(OUTPUT_DIR)/utilities/ColumnType.class \
$(SERVER_DIR)$(OUTPUT_DIR)/utilities/InitFileCommunicator.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/GapListLoader.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/MusicTrack.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/ServerFactory.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/ConnectionBroadcast.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetNextVideoURLCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetCurrentTrackCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SaveGapListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/UnknownCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GapListTrackUpCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetLoadGapListStatusCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SetAsPlayerCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SeekBackwardCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/ChangeGapListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/AddSongToOtherListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/DeleteAllVotesCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetGapListsCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SwitchNotifyStatusCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SetPermissionCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetCurrentGapListNameCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetCurrentPlayerCountCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetCurrentClientCountCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetTitleOfGapListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/CheckIfReadyCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/NotifyClientCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/RegisterCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/DeleteGapListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/VoteForSongCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GetCurrentPlaybackStatusCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/RemoveVoteCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/PauseResumeCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/PlayerFinishedCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SkipCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/GapListTrackDownCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/Command.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/YoutubeCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/SeekForwardCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/commands/DeleteFromListCommand.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/CommandHandler.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/Connection.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/connectivity/ConnectionWaiter.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/VotingController.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/YTJBServer.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/Server.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/player/MusicPlayer.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/player/ClientPlayer.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/player/TrackScheduler.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/player/OMXPlayer.class \
$(SERVER_DIR)$(OUTPUT_DIR)/server/URLParser.class

$(SERVER_DIR)$(OUTPUT_DIR)/%.class: $(SERVER_DIR)$(INPUT_DIR)/%.java
	@echo ""
	@echo "SERVER"
	@echo "------"
	@echo "Creating output folder: $(SERVER_DIR)$(OUTPUT_DIR)"
	@$(MD) $(SERVER_DIR)$(OUTPUT_DIR)
	@echo "Compiling JukePi server"
	@$(JC) $(JFLAGS) -d $(SERVER_DIR)$(OUTPUT_DIR) -cp $(NETWORK_DIR)$(OUTPUT_DIR) $(SERVER_SRC_FILES)


